# Generated by Django 3.0.5 on 2021-04-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_relationship'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='profiles.Profile'),
        ),
    ]
