# Generated by Django 3.0.5 on 2021-04-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210415_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='pdf',
            new_name='user_file',
        ),
    ]
