# Generated by Django 3.0.5 on 2021-04-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_friends'),
        ('documents', '0005_auto_20210416_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.Profile')),
            ],
        ),
    ]
