# Generated by Django 3.0.5 on 2021-04-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20210424_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
    ]
