# Generated by Django 3.0.5 on 2021-04-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20210424_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.Category'),
        ),
    ]
