# Generated by Django 3.0.5 on 2021-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_file_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='category',
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(default=None, null=True, to='documents.Category'),
        ),
    ]
