# Generated by Django 3.0.5 on 2021-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20210425_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(blank=True, to='documents.Category'),
        ),
    ]
