# Generated by Django 3.0.5 on 2021-04-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_subscriptions'),
        ('documents', '0014_auto_20210425_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(null=True, to='documents.Category'),
        ),
    ]
