# Generated by Django 3.0.5 on 2021-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20210427_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='category',
            field=models.ManyToManyField(blank=True, to='documents.Category'),
        ),
    ]
