# Generated by Django 3.0.5 on 2021-04-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
