# Generated by Django 3.0.5 on 2021-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
